export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';
export const EDIT_CUSTOMER= 'EDIT_CUSTOMER';
export const UPDATE_CUSTOMER= 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER= 'DELETE_CUSTOMER';
export const FIND_CUSTOMER= 'FIND_CUSTOMER';
