export const LOAD_CATEGORY = 'LOAD_CATEGORY';
export const EDIT_CATEGORY= 'EDIT_CATEGORY';
export const UPDATE_CATEGORY= 'UPDATE_CATEGORY';
export const DELETE_CATEGORY= 'DELETE_CATEGORY';
export const FIND_CATEGORY= 'FIND_CATEGORY';
