export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const EDIT_PRODUCT= 'EDIT_PRODUCT';
export const UPDATE_PRODUCT= 'UPDATE_PRODUCT';
export const DELETE_PRODUCT= 'DELETE_PRODUCT';
export const LOAD_PRODUCT_BYID= 'LOAD_PRODUCT_BYID';
